apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: ncote-test
  source:
    path: charts
    repoURL: 'https://github.com/NicholasCote/web-viz-charts/tree/main/collection'
    targetRevision: main
  project: ncote